# Generated by Django 5.2.3 on 2025-07-01 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplier_inbound'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('customer', models.CharField(max_length=255)),
                ('so_reference', models.CharField(help_text='Sales order or delivery note reference', max_length=255)),
                ('dispatched_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='outbound_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbounds', to='inventory.product')),
            ],
        ),
    ]
