
services:
  backend:
    build: ./wms-app
    container_name: wms-backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./wms-app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: wms-db
    environment:
      POSTGRES_DB: wmsdb
      POSTGRES_USER: wmsuser
      POSTGRES_PASSWORD: wmspassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: wms-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./wms-frontend/dist:/usr/share/nginx/html:ro
      - ./wms-app/staticfiles:/app/static
      - ./wms-app/media:/app/media
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
